//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietThuePhong
    {
        public int mathuephong { get; set; }
        public string khachhang { get; set; }
        public Nullable<int> vaitro { get; set; }
        public long id { get; set; }
    
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual ThuePhong ThuePhong { get; set; }
    }
}
