//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu
    {
        public DichVu()
        {
            this.ChiTietDichVus = new HashSet<ChiTietDichVu>();
        }
    
        public int madichvu { get; set; }
        public string tendichvu { get; set; }
        public Nullable<decimal> dongia { get; set; }
        public Nullable<int> soluong { get; set; }
        public int loaidichvu { get; set; }
    
        public virtual ICollection<ChiTietDichVu> ChiTietDichVus { get; set; }
        public virtual LoaiDichVu LoaiDichVu1 { get; set; }
    }
}
