//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaTien
    {
        public int id { get; set; }
        public int loaiphong { get; set; }
        public Nullable<decimal> giatien1 { get; set; }
        public string loaigiatien { get; set; }
    
        public virtual LoaiPhong LoaiPhong1 { get; set; }
    }
}
