//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public long mahoadon { get; set; }
        public int mathuephong { get; set; }
        public Nullable<decimal> tongtien { get; set; }
        public Nullable<decimal> tiendatra { get; set; }
        public Nullable<decimal> tienconthua { get; set; }
        public Nullable<System.DateTime> ngaythanhtoan { get; set; }
        public Nullable<decimal> tongtiendichvu { get; set; }
        public Nullable<decimal> tongtienphong { get; set; }
        public int nhanvien { get; set; }
        public string khachhang { get; set; }
    
        public virtual KhachHang KhachHang1 { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual ThuePhong ThuePhong { get; set; }
    }
}
