//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiDichVu
    {
        public LoaiDichVu()
        {
            this.DichVus = new HashSet<DichVu>();
        }
    
        public int Id { get; set; }
        public string tendichvu { get; set; }
    
        public virtual ICollection<DichVu> DichVus { get; set; }
    }
}
