//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoaiPhong
    {
        public LoaiPhong()
        {
            this.GiaTiens = new HashSet<GiaTien>();
            this.Phongs = new HashSet<Phong>();
        }
    
        public int maloaiphong { get; set; }
        public string tenLoaiPhong { get; set; }
        public Nullable<int> soLuongGiuong { get; set; }
    
        public virtual ICollection<GiaTien> GiaTiens { get; set; }
        public virtual ICollection<Phong> Phongs { get; set; }
    }
}
