//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phong
    {
        public Phong()
        {
            this.ThuePhongs = new HashSet<ThuePhong>();
        }
    
        public int id { get; set; }
        public int loaiphong { get; set; }
        public string tenphong { get; set; }
        public Nullable<int> tinhtrang { get; set; }
        public Nullable<int> tang { get; set; }
    
        public virtual LoaiPhong LoaiPhong1 { get; set; }
        public virtual ICollection<ThuePhong> ThuePhongs { get; set; }
    }
}
