//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThuePhong
    {
        public ThuePhong()
        {
            this.ChiTietDichVus = new HashSet<ChiTietDichVu>();
            this.ChiTietThuePhongs = new HashSet<ChiTietThuePhong>();
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int mathuephong { get; set; }
        public int maphong { get; set; }
        public Nullable<System.DateTime> ngaythue { get; set; }
        public Nullable<System.DateTime> ngaytra { get; set; }
    
        public virtual ICollection<ChiTietDichVu> ChiTietDichVus { get; set; }
        public virtual ICollection<ChiTietThuePhong> ChiTietThuePhongs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual Phong Phong { get; set; }
    }
}
